name: Tether
options:
  bundleIdPrefix: com.willhammond.tether
  deploymentTarget:
    macOS: "26.0"
    iOS: "26.0"
  xcodeVersion: "26.0"
  generateEmptyDirectories: true
  groupSortPosition: top

packages:
  TetherKit:
    path: ../TetherKit

settings:
  base:
    SWIFT_VERSION: "6.2"
    MACOSX_DEPLOYMENT_TARGET: "26.0"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: CT65B2T766
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  Tether:
    type: application
    platform: macOS
    sources:
      - path: Tether
        excludes:
          - Resources/Assets.xcassets/AppIcon.appiconset
      - path: TetherMacOS
        excludes:
          - Assets.xcassets
    resources:
      - path: Tether/Resources/Assets.xcassets
      - path: Tether/Resources/Localizable.strings
      - path: TetherMacOS/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.willhammond.tether.app
        PRODUCT_NAME: Tether
        INFOPLIST_GENERATION_MODE: GeneratedFile
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright 2026 Tether. All rights reserved."
        INFOPLIST_KEY_CFBundleDisplayName: Tether
        CODE_SIGN_ENTITLEMENTS: Tether/Tether.entitlements
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        INFOPLIST_KEY_NSCalendarsUsageDescription: "Tether uses your calendar to suggest optimal focus times and avoid scheduling conflicts."
    dependencies:
      - package: TetherKit
        product: TetherKit
      - sdk: AuthenticationServices.framework
      - sdk: EventKit.framework
      - target: TetherSafari
        embed: true
    entitlements:
      path: Tether/Tether.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.network.client: true
        com.apple.security.personal-information.calendars: true
        com.apple.security.application-groups:
          - group.com.willhammond.tether.shared

  TetherIOS:
    type: application
    platform: iOS
    sources:
      - path: TetherIOS
        excludes:
          - Resources/Assets.xcassets/AppIcon.appiconset
    resources:
      - path: TetherIOS/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.willhammond.tether.ios
        PRODUCT_NAME: "Tether"
        INFOPLIST_GENERATION_MODE: GeneratedFile
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_CFBundleDisplayName: Tether
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        IPHONEOS_DEPLOYMENT_TARGET: "26.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        INFOPLIST_KEY_NSCalendarsUsageDescription: "Tether uses your calendar to suggest optimal focus times and avoid scheduling conflicts."
    dependencies:
      - package: TetherKit
        product: TetherKit
      - sdk: AuthenticationServices.framework
      - sdk: EventKit.framework
      - sdk: FamilyControls.framework
      - sdk: ManagedSettings.framework
    entitlements:
      path: TetherIOS/TetherIOS.entitlements
      properties:
        aps-environment: development
        com.apple.developer.family-controls: true
        com.apple.security.application-groups:
          - group.com.willhammond.tether.shared

  TetherSafari:
    type: app-extension
    platform: macOS
    sources:
      - path: TetherSafari
        excludes:
          - Resources
    resources:
      - path: TetherSafari/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.willhammond.tether.app.safari
        PRODUCT_NAME: "Tether Safari"
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: "Tether Focus Blocker"
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright 2026 Tether. All rights reserved."
        CODE_SIGN_ENTITLEMENTS: TetherSafari/TetherSafari.entitlements
        OTHER_LDFLAGS: ["-framework", "SafariServices"]
    dependencies:
      - sdk: SafariServices.framework
    entitlements:
      path: TetherSafari/TetherSafari.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.application-groups:
          - group.com.willhammond.tether.shared

  TetherTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: TetherTests
    dependencies:
      - target: Tether
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.willhammond.tether.tests
        GENERATE_INFOPLIST_FILE: YES

  TetherUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: TetherUITests
    dependencies:
      - target: Tether
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.willhammond.tether.uitests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: Tether
