name: Umbra
options:
  bundleIdPrefix: com.umbra
  deploymentTarget:
    macOS: "26.0"
    iOS: "26.0"
  xcodeVersion: "26.0"
  generateEmptyDirectories: true
  groupSortPosition: top

packages:
  UmbraKit:
    path: ../UmbraKit

settings:
  base:
    SWIFT_VERSION: "6.2"
    MACOSX_DEPLOYMENT_TARGET: "26.0"
    CODE_SIGN_STYLE: Automatic
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  Umbra:
    type: application
    platform: macOS
    sources:
      - path: Umbra
        excludes:
          - Resources/Assets.xcassets/AppIcon.appiconset
    resources:
      - path: Umbra/Resources/Assets.xcassets
      - path: Umbra/Resources/Localizable.strings
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.umbra.app
        PRODUCT_NAME: Umbra
        INFOPLIST_GENERATION_MODE: GeneratedFile
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright 2026 Umbra. All rights reserved."
        INFOPLIST_KEY_CFBundleDisplayName: Umbra
        CODE_SIGN_ENTITLEMENTS: Umbra/Umbra.entitlements
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - package: UmbraKit
        product: UmbraKit
      - sdk: AuthenticationServices.framework
    entitlements:
      path: Umbra/Umbra.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.network.client: true

  UmbraIOS:
    type: application
    platform: iOS
    sources:
      - path: UmbraIOS
        excludes:
          - Resources/Assets.xcassets/AppIcon.appiconset
    resources:
      - path: UmbraIOS/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.umbra.ios
        PRODUCT_NAME: "Umbra"
        INFOPLIST_GENERATION_MODE: GeneratedFile
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_CFBundleDisplayName: Umbra
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        IPHONEOS_DEPLOYMENT_TARGET: "26.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - package: UmbraKit
        product: UmbraKit
      - sdk: AuthenticationServices.framework
      - sdk: FamilyControls.framework
      - sdk: ManagedSettings.framework
    entitlements:
      path: UmbraIOS/UmbraIOS.entitlements
      properties:
        aps-environment: development
        com.apple.developer.family-controls: true
        com.apple.security.application-groups:
          - group.com.umbra.shared

  UmbraTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: UmbraTests
    dependencies:
      - target: Umbra
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.umbra.tests
        GENERATE_INFOPLIST_FILE: YES

  UmbraUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: UmbraUITests
    dependencies:
      - target: Umbra
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.umbra.uitests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: Umbra
